name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version: 10.15.1
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install
    - name: Build pages
      run: npm run build